#!/usr/bin/env sh

# global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# appearance
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

# borders
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

# mouse
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  1
yabai -m config bottom_padding               1
yabai -m config left_padding                 1
yabai -m config right_padding                1
yabai -m config window_gap                   1

yabai -m space --create


echo "yabai configuration loaded.."
