#!/bin/bash

# global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# appearance
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

# borders
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

# mouse
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  1
yabai -m config bottom_padding               1
yabai -m config left_padding                 1
yabai -m config right_padding                1
yabai -m config window_gap                   1

num_spaces=6

while [ "$(yabai -m query --spaces | jq length)" -lt ${num_spaces} ]; do
  yabai -m space --create
done

yabai -m space 1 --label term
yabai -m space 2 --label browser
yabai -m space 3 --label code
yabai -m space 4 --label mail
yabai -m space 5 --label varia
yabai -m space 6 --label chat

yabai -m rule --add app=Brave space=browser
yabai -m rule --add app=Atom space=code
yabai -m rule --add app=Mail space=mail
yabai -m rule --add app=Franz space=chat
yabai -m rule --add app=Ferdi space=chat

echo "yabai configuration loaded..."
