name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: ./install.sh --only-deps
      - name: Install dotfiles
        run: export DOTFILES="$(pwd)" && dotfile_manager install
      - name: Setup dotfiles
        run: dotfile_manager setup
