name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: ./install.sh --only-install-dependencies.sh
      - name: Install dotfiles
        run: export DOTFILES="$(pwd)" && dotfile_manager install
      - name: Setup dotfiles
        run: dotfile_manager setup
